---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: tls-transport
  namespace: default

spec:
  serverName: api
  rootCAsSecrets:
    - ca-cert
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-api-prefix
  namespace: default

spec:
  stripPrefix:
    prefixes:
      - /api/v1
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-ingress
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: PathPrefix(`/api/v1`)
    services:
    - name: api
      port: 443
      serversTransport: tls-transport
    middlewares:
    - name: strip-api-prefix
  tls:
    secretName: api-tls
