---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-api-prefix
  namespace: kube-system
spec:
  stripPrefix:
    prefixes:
      - /api/v1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apigateway
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-strip-api-prefix@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              name: http
