apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api
spec:
  secretName: api-tls
  duration: 168h # 7d
  renewBefore: 72h # 3d
  subject:
    organizations:
      - fintech-devcon-jumpwire-workshop
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - client auth
  dnsNames:
    # adding localhost to allow TLS validation when port-forwarding
    # for local dev
    - localhost
    - api
    - api.default.svc.cluster.local
    - api.svc.cluster.local
    - api.cluster.local
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
