apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress
spec:
  secretName: ingress-tls
  duration: 168h # 7d
  renewBefore: 72h # 3d
  subject:
    organizations:
      - fintech-devcon-jumpwire-workshop
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
  dnsNames:
    # adding localhost to allow TLS validation when port-forwarding
    # for local dev
    - localhost
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
