apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres
spec:
  secretName: postgres-tls
  duration: 168h # 7d
  renewBefore: 72h # 3d
  subject:
    organizations:
      - fintech-devon-jumpwire-workshop
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - client auth
  dnsNames:
    # adding localhost to allow TLS validation when port-forwarding
    # for local dev
    - localhost
    - postgres
    - postgres.default.svc.cluster.local
    - postgres.svc.cluster.local
    - postgres.cluster.local
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
